name: release AppImage

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 libudev-dev

      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: checkout
        uses: actions/checkout@v4

      - name: install Node dependencies
        run: pnpm install

      - name: build linux AppImage
        run: pnpm run build:linux-x64

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/nanokvm-usb-${{ github.ref_name }}-linux-x64.AppImage
